version: '3.3'
services:
  reverse-proxy:
    build:
      context: ./
    image: michaelmason1998/portfolio_nginx_server
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - "app-network"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
networks:
  app-network:
    external: true